import type { TargetCompany } from '@/types';

export const mockCompanies: TargetCompany[] = [
  {
    id: 'comp-1',
    name: 'サンプルコンサルティング',
    industry: 'ITコンサルティング',
    address: '東京都千代田区丸の内2-1-1',
    employeeCount: '500名',
    revenue: '85億円',
    founded: '2012年',
    logoInitials: 'SC',
    logoColor: 'bg-blue-600',
    overallMatch: 85,
    businessSummary:
      'DX推進・業務改善・生成AI導入支援を行う総合コンサルティング企業。大手製造・金融・小売業を中心に年間100件以上のプロジェクトを手がけ、成果報酬型のエンゲージメントモデルで顧客から高い評価を受けている。',
    tags: ['成長環境', '裁量あり', '高年収'],
    recommendationReason: 'あなたの課題解決力と調整力を活かしやすい',
    matchScores: {
      skill: 85, values: 80, career: 88, salary: 82,
      workStyle: 70, growth: 90, stability: 65, autonomy: 85,
      relationship: 75, industryInterest: 80, location: 90, companySize: 75,
    },
    aiComment:
      'この企業はあなたの調整力や課題解決力を直接活かせる環境が揃っています。一方、プロジェクト繁忙期の業務量増加には事前に備えておく必要があります。',
    reasons: [
      'コンサルタントとして培った課題解決・提案スキルが即戦力として評価される',
      '成果主義の評価制度が「正当な評価を受けたい」という価値観と一致',
      '明確なキャリアパス（コンサルタント→マネージャー→パートナー）が用意されている',
    ],
    risks: [
      'プロジェクト繁忙期は月残業40〜60hに達するケースがある',
      '社内昇進には特定の資格取得や社内審査が必要で、時間がかかる場合がある',
    ],
    postings: [
      {
        id: 'jp-1-1',
        title: 'ITコンサルタント（DX推進）',
        salary: '700〜950万円',
        location: '東京・大阪（リモート可）',
        employmentType: '正社員',
        requirements: ['コンサルまたはIT業界3年以上', 'プロジェクトリード経験', 'ロジカルシンキング'],
        welcomeRequirements: ['PMP/ITILなどの資格', 'AI/ML基礎知識', '英語ビジネスレベル'],
        difficulty: '普通',
        postedAt: '2026-04-15',
        deadline: '2026-06-30',
      },
      {
        id: 'jp-1-2',
        title: 'シニアコンサルタント（事業変革）',
        salary: '900〜1,200万円',
        location: '東京（リモート可）',
        employmentType: '正社員',
        requirements: ['コンサル5年以上', 'チームリード経験', '事業戦略立案経験'],
        welcomeRequirements: ['MBA', '事業会社での勤務経験', 'クライアント開拓経験'],
        difficulty: '難',
        postedAt: '2026-04-01',
        deadline: '2026-07-31',
      },
    ],
  },
  {
    id: 'comp-2',
    name: 'ネクストデジタル',
    industry: 'SaaS',
    address: '東京都渋谷区道玄坂1-2-3',
    employeeCount: '300名',
    revenue: '45億円',
    founded: '2018年',
    logoInitials: 'ND',
    logoColor: 'bg-violet-600',
    overallMatch: 78,
    businessSummary:
      '中堅〜大手法人向けSaaSプロダクトの開発・販売を行う成長スタートアップ。マーケティングオートメーション領域で急成長中。年30%以上の売上成長率を維持しており、直近シリーズC資金調達を完了。',
    tags: ['成長環境', 'スピード感', 'プロダクト志向'],
    recommendationReason: '事業企画やAI活用の経験を伸ばしやすい',
    matchScores: {
      skill: 78, values: 76, career: 82, salary: 75,
      workStyle: 80, growth: 88, stability: 60, autonomy: 82,
      relationship: 70, industryInterest: 85, location: 88, companySize: 70,
    },
    aiComment:
      'スピーディーな意思決定環境があなたの「成長実感の不足」というストレス要因を解消できる可能性が高いです。ただし組織整備が途上の部分があるため、自走力が必要です。',
    reasons: [
      '裁量の大きな環境で実行力を発揮できる',
      'AI活用・DX領域への転換という志向と事業ドメインが一致',
      '30歳前後でのマネージャー登用実績があり、キャリアアップが早い',
    ],
    risks: [
      'SaaSプロダクトへの深い理解が求められ、初期キャッチアップに3〜6ヶ月かかる',
      'スタートアップ文化への適応が必要（プロセス未整備の部分がある）',
    ],
    postings: [
      {
        id: 'jp-2-1',
        title: 'プロダクトマネージャー（BtoB SaaS）',
        salary: '700〜900万円',
        location: '東京（週2リモート可）',
        employmentType: '正社員',
        requirements: ['BtoB SaaSのPMまたはコンサル経験3年以上', 'ユーザーヒアリング・仕様策定経験'],
        welcomeRequirements: ['SQL基礎', 'A/Bテスト経験', 'スタートアップ経験'],
        difficulty: '普通',
        postedAt: '2026-04-20',
        deadline: '2026-05-31',
      },
    ],
  },
  {
    id: 'comp-3',
    name: 'グロースキャリア',
    industry: '人材・HRTech',
    address: '東京都港区赤坂3-4-5',
    employeeCount: '350名',
    revenue: '45億円',
    founded: '2015年',
    logoInitials: 'GC',
    logoColor: 'bg-emerald-600',
    overallMatch: 72,
    businessSummary:
      'AIマッチングと人的支援を組み合わせた人材紹介・HR支援サービスを提供するHRTech企業。転職者の長期定着率90%超を実現する独自のオンボーディング支援が強み。副業・社内起業制度あり。',
    tags: ['HRTech', '人材支援', '社会貢献'],
    recommendationReason: '人の成長支援という価値観と相性が良い',
    matchScores: {
      skill: 70, values: 85, career: 75, salary: 65,
      workStyle: 72, growth: 78, stability: 70, autonomy: 68,
      relationship: 82, industryInterest: 74, location: 88, companySize: 68,
    },
    aiComment:
      '「誰かの役に立っている実感」がモチベーション源のあなたには、人材支援という仕事の性質が深く合致します。ただし売上数字へのコミットが強い文化には慣れが必要です。',
    reasons: [
      '1on1文化・評価の透明性が「評価への不満」というストレス要因を解消できる',
      'HRTech × コンサルの希少人材として市場価値を高めるキャリアパスがある',
      '副業・社内起業制度があり、長期的な独立志向とも両立しやすい',
    ],
    risks: [
      'ITコンサルから人材業界へのピボットは初期の学習コストが高い',
      '売上インセンティブ文化への適応が必要（数字へのコミットが強い）',
    ],
    postings: [
      {
        id: 'jp-3-1',
        title: 'HRコンサルタント（エンタープライズ）',
        salary: '550〜750万円',
        location: '東京（週2リモート）',
        employmentType: '正社員',
        requirements: ['法人営業またはコンサル経験2年以上', '人事・採用領域の基礎知識'],
        welcomeRequirements: ['人材業界経験', 'HR領域のプロジェクト経験'],
        difficulty: '易',
        postedAt: '2026-03-15',
        deadline: '2026-06-15',
      },
      {
        id: 'jp-3-2',
        title: 'プロダクトマネージャー（HRTech）',
        salary: '650〜900万円',
        location: '東京（フルリモート可）',
        employmentType: '正社員',
        requirements: ['PM経験2年以上またはコンサル経験3年以上', 'データドリブンな意思決定経験'],
        welcomeRequirements: ['HR/採用領域の知識', 'AIプロダクト開発経験'],
        difficulty: '難',
        postedAt: '2026-04-01',
      },
    ],
  },
  {
    id: 'comp-4',
    name: 'イノベーションキャピタル',
    industry: 'VC・スタートアップ支援',
    address: '東京都港区六本木6-7-8',
    employeeCount: '120名',
    revenue: '30億円（管理AUM：500億円）',
    founded: '2010年',
    logoInitials: 'IC',
    logoColor: 'bg-amber-500',
    overallMatch: 68,
    businessSummary:
      '国内外のスタートアップへの投資・支援を行うベンチャーキャピタル。ポートフォリオ企業への経営支援・人材紹介・DX支援を通じて、起業家と事業成長をサポート。',
    tags: ['起業家思考', '高裁量', 'ネットワーク'],
    recommendationReason: '将来の独立・事業開発志向と長期的に合致する',
    matchScores: {
      skill: 72, values: 78, career: 80, salary: 68,
      workStyle: 75, growth: 85, stability: 45, autonomy: 90,
      relationship: 80, industryInterest: 88, location: 85, companySize: 60,
    },
    aiComment:
      '「自分の力で事業を生み出したい」というビジョンを持つあなたには、スタートアップエコシステムの中核にいるVC業務は長期的なキャリア資産になります。ただし基本給は他社より低い傾向があります。',
    reasons: [
      '投資先スタートアップのDX支援でコンサル経験を活かしつつ、起業家マインドを学べる',
      '多様な業界・事業を横断的に学べるため、将来の起業・独立への視野が広がる',
      '裁量90点：自分で投資判断・支援策を提案できる高い自律性',
    ],
    risks: [
      '基本給は大手コンサルより低いケースが多く、年収ダウンの可能性',
      '不確実性の高い環境を楽しめるマインドセットが必要',
    ],
    postings: [
      {
        id: 'jp-4-1',
        title: 'バリューアップコンサルタント（ポートフォリオ支援）',
        salary: '600〜850万円',
        location: '東京（フレックス）',
        employmentType: '正社員',
        requirements: ['コンサルまたは事業会社での戦略・DX経験3年以上', 'スタートアップへの理解'],
        welcomeRequirements: ['起業・副業経験', '英語ビジネスレベル', 'ファイナンス基礎'],
        difficulty: '難',
        postedAt: '2026-04-10',
        deadline: '2026-08-31',
      },
    ],
  },
];
